# Generated by Django 3.2.19 on 2026-08-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
